config/routes.rb
Rails.application.routes.draw do
  get '/blogs' => 'blog#index', as:'blogs'
  get '/blogs/new' => 'blog#new', as: 'new_blog'
  get '/blogs/:id' => 'blog#show', as: 'blog'
  post 'blogs' => 'blog#create'
  delete '/blogs/:id' => 'blog#destroy', as: 'delete_blog'

  root "blog#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @blogs = Blog.all
    end
    def show
        @blog = Blog.find(params[:id])
    end
    def new
        @blog = Blog.new
    end
    def create
        @blog = Blog.create (blog_params)
        if @blog.valid?
        redirect_to blogs_path
        end
    end
    def destroy
        @blog = Blog.find(params[:id])
        if @blog.destroy
        redirect_to blogs_path
        end
    end
    private
    def blog_params
        params.require(:blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/index.html.erb
<h1>Blog Titles</h1>

<ul>
    <% @blogs.each do |blog| %>
        <li>
            <%= link_to blog.title, blog_path(blog) %>
        </li>
    <% end %>
</ul>
<%= link_to 'Add a Blog', new_blog_path %>

app/views/blog/new.html.erb
<h3>Add a New Blog</h3>
<%= form_with model: @blog do |form| %>
    <%= form.text_field :title %>
    <br></br>
    <%= form.text_area :content %>
    <br></br>
    <%= form.submit %>
<% end %>

app/views/blog/show.html.erb
<h3><%= @blog.title %></h3>
<p><%= @blog.content %></p>

<%= button_to 'Remove Blog', delete_blog_path, method: 'delete' %>
<br/>
<h5><%= link_to 'Back to Blogs', blogs_path %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStackRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>